server:
  port: 9090

spring:
  application:
    name: msvc-course
  data-source:
    driver-class-name: org.postgresql.Driver
    url : jdbc:postgresql://localhost:5432/coursesDb
    username: postgres
    password : SpringClase
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
